server:
  port: 5001
  servlet:
    context-path: /profile # This is the context path for the application use in load balancer


spring:
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: 12345678